apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: alertmanager-dingtalk
  labels:
    k8s.kuboard.cn/layer: svc
    app: alertmanager-dingtalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-dingtalk
  template:
    metadata:
      labels:
        app: alertmanager-dingtalk
    spec:
      imagePullSecrets:
        - name: image-secret
      containers:
        - name: alertmanager-dingtalk
          imagePullPolicy: IfNotPresent
          image: llybood/alertmanager-dingtalk:latest
          ports:
            - containerPort: 8111
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '0.1'
              memory: 100Mi
          volumeMounts:
            - name: alertmanager-dingtalk-conf
              mountPath: /app/alertmanager-dingtalk/config/config.yaml
              subPath: config.yaml
            - name: alertmanager-dingtalk-templat
              mountPath: /app/alertmanager-dingtalk/template/template.tmpl
              subPath: template.tmpl
      restartPolicy: Always
      volumes:
        - configMap:
            name: alertmanager-dingtalk-conf
          name: alertmanager-dingtalk-conf
        - configMap:
            name: alertmanager-dingtalk-templat
          name: alertmanager-dingtalk-templat


---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: alertmanager-dingtalk
spec:
  selector:
    app: alertmanager-dingtalk
  ports:
    - protocol: TCP
      name: http
      port: 8111
      targetPort: 8111
  sessionAffinity: None
  type: ClusterIP

