{
 "title": "llm-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "一分钟内请求成功数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_vts_upstream_requests_total{job=\"NGINX_VTS_EXPORTER\",upstream=~\"tianshu.*|Qwen.*|ocr.*\",code=\"2xx\"}[1m]) * 60",
     "legendFormat": "{{upstream}}-{{backend}}"
    }
   ]
  },
  {
   "title": "请求模型耗时",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nginx_vts_upstream_request_seconds{job=\"NGINX_VTS_EXPORTER\",upstream=~\"tianshu.*|Qwen.*|ocr.*\"}*1000",
     "legendFormat": "{{upstream}}-{{backend}}"
    }
   ]
  },
  {
   "title": "请求saas耗时",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nginx_vts_upstream_request_seconds{job=\"NGINX_VTS_EXPORTER\",upstream=~\"iio-proxy.*\"}*1000",
     "legendFormat": "{{upstream}}-{{backend}}"
    }
   ]
  }
 ]
}