{
 "title": "ascend-npu-exporter2",
 "description": "「Ascend Npu Monitor」\r\nA Grafana dashboard for monitoring Ascend NPU metrics via ascend-npu-exporter. Visualize AI Core utilization, temperature, power, memory, and network status in real time.\r\n基于 ascend-npu-exporter 的昇腾NPU监控面板，支持AI Core、温度、功耗、内存、网络等关键指标的实时可视化。",
 "tags": [
  "ascend",
  "昇腾"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "JOB",
    "query": {
     "query": "label_values(npu_chip_info_name{}, job)"
    }
   },
   {
    "name": "instance",
    "label": "实例名",
    "query": {
     "query": "label_values(npu_chip_info_name{job=~\"$job_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "昇腾AI处理器数目",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_npu_nums{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器的AI Core当前频率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_aicore_current_freq{instance=\"$instance\",id=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器健康状态",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "npu_chip_info_health_status{instance=\"$instance\"}",
     "legendFormat": "NPU_{{id}}健康状态"
    }
   ]
  },
  {
   "title": "NPU显存利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "npu_chip_info_hbm_used_memory{instance=\"$instance\"}/npu_chip_info_hbm_total_memory{instance=\"$instance\"}*100",
     "legendFormat": "NPU-{{id}}_显存使用率"
    }
   ]
  },
  {
   "title": "NPU显存使用大小",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "npu_chip_info_hbm_used_memory{instance=\"$instance\"}",
     "legendFormat": "NPU-{{id}}_已用内存"
    }
   ]
  },
  {
   "title": "昇腾AI处理器进程占用内存信息",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "repeat": "npu_id",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "npu_chip_info_process_info{instance=\"$instance\"}",
     "legendFormat": "NPU_{{id}}_进程{{process_id}}"
    }
   ]
  },
  {
   "title": "昇腾AI处理器AI Core利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "npu_chip_info_utilization{instance=\"$instance\"}",
     "legendFormat": "NPU_{{id}}利用率"
    }
   ]
  },
  {
   "title": "昇腾AI处理器功耗",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "npu_chip_info_power{instance=\"$instance\"}",
     "legendFormat": "NPU_{{id}}AI处理器功耗"
    }
   ]
  },
  {
   "title": "昇腾AI处理器温度",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "npu_chip_info_temperature{instance=\"$instance\"}",
     "legendFormat": "NPU_{{id}}AI处理器温度"
    }
   ]
  }
 ]
}