{
 "title": "GPU-Nodes-Metrics-Nvidia",
 "description": "使用NVIDIA Data Center GPU Manager (DCGM) dcgm-exporter 通过Prometheus绘制的GPU Nvidia 基础监控信息.",
 "tags": [
  "IB",
  "GPU"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "gpu_host",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{job=\"nvidia_dcgm-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{instance=~\"$hostname\"}*1000000)",
     "legendFormat": "GPU SM 时钟"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{instance=~\"$hostname\"}*1000000)",
     "legendFormat": "GPU 内存时钟"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Mem Cpy Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}/(DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}+DCGM_FI_DEV_FB_FREE{instance=~\"$hostname\"}))*100",
     "legendFormat": "GPU-{{gpu}} 内存使用率"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$hostname\"}",
     "legendFormat": "GPU-{{gpu}} 利用率"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$hostname\"} ",
     "legendFormat": "GPU-{{gpu}} 温度 "
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$hostname\"}",
     "legendFormat": "GPU-{{gpu}} 功率"
    }
   ]
  },
  {
   "title": "GPU 内存使用",
   "type": "timeseries",
   "description": "内存使用",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}",
     "legendFormat": "GPU-{{gpu}} 显存占用"
    }
   ]
  }
 ]
}