{
 "title": "GPU-Nodes-Metrics-Nvidia",
 "description": "使用NVIDIA Data Center GPU Manager (DCGM) dcgm-exporter 通过Prometheus绘制的GPU Nvidia 基础监控信息.",
 "tags": [
  "IB",
  "GPU"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "gpu_host",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL{job=\"gpu\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{instance=~\"$hostname\"}*1000000)",
     "legendFormat": "GPU SM 时钟"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{instance=~\"$hostname\"}*1000000)",
     "legendFormat": "GPU 内存时钟"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}/(DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}+DCGM_FI_DEV_FB_FREE{instance=~\"$hostname\"}))*100",
     "legendFormat": "GPU 内存使用率  {{instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$hostname\"}",
     "legendFormat": "GPU 使用率 {{instance}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Mem Cpy Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$hostname\"}",
     "legendFormat": "GPU 功率 {{instance}}"
    }
   ]
  },
  {
   "title": "GPU Mem Copy Utilization",
   "type": "timeseries",
   "description": "内存利用率\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$hostname\"}",
     "legendFormat": "GPU 内存利用率 {{instance}}"
    }
   ]
  },
  {
   "title": "GPU 内存使用",
   "type": "timeseries",
   "description": "内存使用",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}+DCGM_FI_DEV_FB_FREE{instance=~\"$hostname\"}",
     "legendFormat": "GPU 总内存"
    },
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$hostname\"}",
     "legendFormat": "GPU 已用内存"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$hostname\"} ",
     "legendFormat": "GPU 温度 {{instance}}"
    }
   ]
  }
 ]
}